import getPadsForExport, {
  findExtent,
  findPixelCenter,
  getPadPixelCoords
} from '../getPadsForExport';

import * as hexUnixSeconds from '../hexUnixSeconds';

import TEST_CANVAS from './data/canvas';
const TEST_SCALE_FACTOR = 120;

test('findExtent()', () => {
  expect(findExtent(TEST_CANVAS._objects)).toEqual([396, 219, 702, 651]);
});

test('findPixelCenter()', () => {
  expect(findPixelCenter([396, 219, 702, 651])).toEqual([549, 435]);
});

test('getPadPixelCoords()', () => {
  const obj = {
    left: 396,
    top: 219,
    width: 100,
    height: 100,
    scaleX: 0.8,
    scaleY: 1.22
  };
  const pixelCoords = getPadPixelCoords(obj, [549, 435]);

  expect(pixelCoords).toEqual({
    ...obj,
    pixelCenter: [-113, -155]
  });
});

test('getPadsForExport()', () => {
  const physicalCoords = getPadsForExport(TEST_CANVAS, TEST_SCALE_FACTOR);

  expect(physicalCoords).toEqual([
    {
      angle: 0,
      backgroundColor: '',
      clipTo: null,
      fill: 'red',
      fillRule: 'nonzero',
      flipX: false,
      flipY: false,
      globalCompositeOperation: 'source-over',
      height: 100,
      isPad: true,
      left: 396,
      opacity: 1,
      originX: 'left',
      originY: 'top',
      paintFirst: 'fill',
      physicalHeight: 1.0166666666666666,
      physicalWidth: 0.6666666666666666,
      physicalX: -0.9416666666666667,
      physicalY: -1.2916666666666667,
      pixelCenter: [-113, -155],
      rx: 0,
      ry: 0,
      scaleX: 0.8,
      scaleY: 1.22,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: null,
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: 'butt',
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 219,
      transformMatrix: null,
      type: 'rect',
      version: '2.7.0',
      visible: true,
      width: 100
    },
    {
      angle: 0,
      backgroundColor: '',
      clipTo: null,
      fill: 'red',
      fillRule: 'nonzero',
      flipX: false,
      flipY: false,
      globalCompositeOperation: 'source-over',
      height: 100,
      isPad: true,
      left: 510,
      opacity: 1,
      originX: 'left',
      originY: 'top',
      paintFirst: 'fill',
      physicalHeight: 1.0083333333333333,
      physicalWidth: 0.6583333333333333,
      physicalX: 0.004166666666666667,
      physicalY: -1.2875,
      pixelCenter: [0.5, -154.5],
      rx: 0,
      ry: 0,
      scaleX: 0.79,
      scaleY: 1.21,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: null,
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: 'butt',
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 220,
      transformMatrix: null,
      type: 'rect',
      version: '2.7.0',
      visible: true,
      width: 100
    },
    {
      angle: 0,
      backgroundColor: '',
      clipTo: null,
      fill: 'red',
      fillRule: 'nonzero',
      flipX: false,
      flipY: false,
      globalCompositeOperation: 'source-over',
      height: 100,
      isPad: true,
      left: 623,
      opacity: 1,
      originX: 'left',
      originY: 'top',
      paintFirst: 'fill',
      physicalHeight: 1,
      physicalWidth: 0.6583333333333333,
      physicalX: 0.9458333333333333,
      physicalY: -1.2916666666666667,
      pixelCenter: [113.5, -155],
      rx: 0,
      ry: 0,
      scaleX: 0.79,
      scaleY: 1.2,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: null,
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: 'butt',
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 220,
      transformMatrix: null,
      type: 'rect',
      version: '2.7.0',
      visible: true,
      width: 100
    },
    {
      angle: 0,
      backgroundColor: '',
      clipTo: null,
      fill: 'red',
      fillRule: 'nonzero',
      flipX: false,
      flipY: false,
      globalCompositeOperation: 'source-over',
      height: 100,
      isPad: true,
      left: 397,
      opacity: 1,
      originX: 'left',
      originY: 'top',
      paintFirst: 'fill',
      physicalHeight: 1.0083333333333333,
      physicalWidth: 0.6583333333333333,
      physicalX: -0.9375,
      physicalY: 1.2958333333333334,
      pixelCenter: [-112.5, 155.5],
      rx: 0,
      ry: 0,
      scaleX: 0.79,
      scaleY: 1.21,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: null,
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: 'butt',
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 530,
      transformMatrix: null,
      type: 'rect',
      version: '2.7.0',
      visible: true,
      width: 100
    },
    {
      angle: 0,
      backgroundColor: '',
      clipTo: null,
      fill: 'red',
      fillRule: 'nonzero',
      flipX: false,
      flipY: false,
      globalCompositeOperation: 'source-over',
      height: 100,
      isPad: true,
      left: 623,
      opacity: 1,
      originX: 'left',
      originY: 'top',
      paintFirst: 'fill',
      physicalHeight: 1.0083333333333333,
      physicalWidth: 0.6583333333333333,
      physicalX: 0.9458333333333333,
      physicalY: 1.2958333333333334,
      pixelCenter: [113.5, 155.5],
      rx: 0,
      ry: 0,
      scaleX: 0.79,
      scaleY: 1.21,
      shadow: null,
      skewX: 0,
      skewY: 0,
      stroke: null,
      strokeDashArray: null,
      strokeDashOffset: 0,
      strokeLineCap: 'butt',
      strokeLineJoin: 'miter',
      strokeMiterLimit: 4,
      strokeWidth: 1,
      top: 530,
      transformMatrix: null,
      type: 'rect',
      version: '2.7.0',
      visible: true,
      width: 100
    }
  ]);
});
